scrape_configs:
  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb1:9216', 'mongodb2:9216', 'mongodb_arbiter:9216']
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
